/**
 * PDF Executive Summary Generator
 * 
 * Creates a polished one-page PDF summary when a journey + dashboard is created.
 * Branded with Dynatrace colors and designed for sales/business conversations.
 * 
 * Uses PDFKit (already in package.json) — no browser/puppeteer dependency.
 */

import PDFDocument from 'pdfkit';

// ── Dynatrace Brand Colors ─────────────────────────────────
const COLORS = {
  dtPurple:   '#6C2C9C',
  dtCyan:     '#00D4FF',
  dtGreen:    '#73BE28',
  dtBlue:     '#00A1C9',
  dtOrange:   '#FFA86B',
  dtYellow:   '#FFD23F',
  dtDark:     '#181A20',
  dtCard:     '#22242A',
  dtGray:     '#2D2F36',
  white:      '#FFFFFF',
  lightGray:  '#B0B0B0',
  midGray:    '#6B7280',
};

// ── Industry icons (unicode) ────────────────────────────────
const INDUSTRY_ICONS = {
  'e-commerce':     '🛒',
  'retail':         '🛍️',
  'banking':        '🏦',
  'financial':      '💰',
  'insurance':      '🛡️',
  'telecom':        '📡',
  'travel':         '✈️',
  'hospitality':    '🏨',
  'manufacturing':  '🏭',
  'media':          '📺',
  'healthcare':     '🏥',
  'default':        '📊',
};

// ── Category to business value mapping ──────────────────────
const CATEGORY_VALUES = {
  'Acquisition':          'Customer engagement & conversion entry point',
  'FulfilmentPreparation':'Operational readiness & capacity management',
  'Purchase':             'Revenue capture & checkout optimization',
  'Payment':              'Payment success rate & fraud prevention',
  'Confirmation':         'Order confirmation & customer confidence',
  'Delivery':             'Fulfilment performance & customer satisfaction',
  'PostPurchase':         'Retention, loyalty & lifetime value',
  'Decisioning':          'Automated decision speed & accuracy',
  'Conversion':           'Conversion rate optimization',
  'Compliance':           'Regulatory compliance & risk management',
  'Onboarding':           'Time-to-value & first experience quality',
  'Support':              'Resolution time & customer effort score',
};

/**
 * Generate a one-page executive summary PDF
 * 
 * @param {Object} options
 * @param {Object} options.journeyData - The journey configuration (company, steps, etc.)
 * @param {Object} options.dashboardData - The generated dashboard metadata (tile count, detected fields, etc.)
 * @returns {Promise<Buffer>} PDF as a Buffer
 */
export function generateExecutiveSummaryPDF({ journeyData, dashboardData }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 0,
        info: {
          Title: `${journeyData.companyName || journeyData.company || 'Customer'} — Business Observability Summary`,
          Author: 'Business Observability Forge — Dynatrace',
          Subject: 'Executive Summary — Journey & Dashboard Overview',
          Creator: 'BizObs Forge PDF Generator',
        }
      });

      const buffers = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const company = journeyData.companyName || journeyData.company || 'Customer';
      const industry = journeyData.industryType || journeyData.industry || 'Enterprise';
      const journeyType = journeyData.journeyType || journeyData.journeyDetail || 'Customer Journey';
      const steps = journeyData.steps || [];
      const metadata = dashboardData?.metadata || dashboardData || {};
      const detectedFlags = metadata?.detectedFields?.flags || {};

      const PAGE_W = 595.28;
      const PAGE_H = 841.89;
      const MARGIN = 36;
      const CONTENT_W = PAGE_W - (MARGIN * 2);

      // ══════════════════════════════════════════════════════
      // HEADER BAR — Gradient-style dark banner
      // ══════════════════════════════════════════════════════
      doc.rect(0, 0, PAGE_W, 90).fill(COLORS.dtDark);
      doc.rect(0, 86, PAGE_W, 4).fill(COLORS.dtCyan);

      // Title
      doc.fontSize(22).fillColor(COLORS.white)
        .text('Business Observability', MARGIN, 18, { continued: true })
        .fillColor(COLORS.dtCyan).text(' Summary');
      
      doc.fontSize(9).fillColor(COLORS.lightGray)
        .text('Powered by Dynatrace  |  Generated by Business Observability Forge', MARGIN, 52);
      
      doc.fontSize(8).fillColor(COLORS.midGray)
        .text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), MARGIN, 68);

      // ══════════════════════════════════════════════════════
      // COMPANY / JOURNEY HEADER
      // ══════════════════════════════════════════════════════
      let y = 104;

      const icon = getIndustryIcon(industry);
      doc.fontSize(20).fillColor(COLORS.dtPurple)
        .text(`${icon}  ${company}`, MARGIN, y);
      y += 28;

      doc.fontSize(11).fillColor(COLORS.midGray)
        .text(`${industry}  •  ${journeyType}  •  ${steps.length} Steps`, MARGIN, y);
      y += 24;

      // ══════════════════════════════════════════════════════
      // JOURNEY FLOW — Visual step pipeline
      // ══════════════════════════════════════════════════════
      doc.rect(MARGIN, y, CONTENT_W, 1).fill(COLORS.dtCyan);
      y += 10;

      doc.fontSize(10).fillColor(COLORS.dtCyan)
        .text('JOURNEY FLOW', MARGIN, y);
      y += 18;

      // Draw step boxes
      const maxSteps = Math.min(steps.length, 6);
      const boxW = (CONTENT_W - (maxSteps - 1) * 8) / maxSteps;
      const boxH = 54;

      const stepColors = [COLORS.dtPurple, COLORS.dtBlue, COLORS.dtCyan, COLORS.dtGreen, COLORS.dtOrange, COLORS.dtYellow];

      for (let i = 0; i < maxSteps; i++) {
        const step = steps[i];
        const x = MARGIN + i * (boxW + 8);
        const color = stepColors[i % stepColors.length];

        // Step box
        doc.roundedRect(x, y, boxW, boxH, 4).fill(COLORS.dtCard);
        doc.roundedRect(x, y, boxW, 3, 1).fill(color);

        // Step number + name
        doc.fontSize(6).fillColor(color)
          .text(`STEP ${i + 1}`, x + 6, y + 8, { width: boxW - 12 });

        const stepName = formatStepName(step.stepName || `Step ${i + 1}`);
        doc.fontSize(7).fillColor(COLORS.white)
          .text(stepName, x + 6, y + 18, { width: boxW - 12, lineBreak: true, height: 16, ellipsis: true });

        // Duration
        doc.fontSize(6).fillColor(COLORS.midGray)
          .text(`${step.estimatedDuration || '?'}min`, x + 6, y + 40, { width: boxW - 12 });

        // Arrow between steps
        if (i < maxSteps - 1) {
          const arrowX = x + boxW + 1;
          doc.fontSize(8).fillColor(COLORS.midGray)
            .text('→', arrowX, y + 20);
        }
      }

      y += boxH + 16;

      // ══════════════════════════════════════════════════════
      // WHAT DYNATRACE OBSERVES — Key metrics grid
      // ══════════════════════════════════════════════════════
      doc.rect(MARGIN, y, CONTENT_W, 1).fill(COLORS.dtGreen);
      y += 10;

      doc.fontSize(10).fillColor(COLORS.dtGreen)
        .text('WHAT DYNATRACE NOW OBSERVES', MARGIN, y);
      y += 18;

      // Build metrics based on detected flags
      const observedMetrics = buildObservedMetrics(detectedFlags, steps, industry);
      const metricCols = 3;
      const metricW = (CONTENT_W - (metricCols - 1) * 10) / metricCols;
      const metricH = 52;

      for (let i = 0; i < Math.min(observedMetrics.length, 9); i++) {
        const col = i % metricCols;
        const row = Math.floor(i / metricCols);
        const x = MARGIN + col * (metricW + 10);
        const my = y + row * (metricH + 8);

        const metric = observedMetrics[i];

        doc.roundedRect(x, my, metricW, metricH, 4).fill(COLORS.dtCard);
        doc.roundedRect(x, my, 3, metricH, 1).fill(metric.color);

        doc.fontSize(14).fillColor(metric.color)
          .text(metric.icon, x + 10, my + 8);

        doc.fontSize(8).fillColor(COLORS.white)
          .text(metric.title, x + 30, my + 8, { width: metricW - 40 });

        doc.fontSize(6.5).fillColor(COLORS.lightGray)
          .text(metric.description, x + 30, my + 22, { width: metricW - 40, lineBreak: true, height: 22 });
      }

      const metricRows = Math.ceil(Math.min(observedMetrics.length, 9) / metricCols);
      y += metricRows * (metricH + 8) + 8;

      // ══════════════════════════════════════════════════════
      // BUSINESS VALUE — What this means for them
      // ══════════════════════════════════════════════════════
      doc.rect(MARGIN, y, CONTENT_W, 1).fill(COLORS.dtPurple);
      y += 10;

      doc.fontSize(10).fillColor(COLORS.dtPurple)
        .text('BUSINESS VALUE WITH DYNATRACE', MARGIN, y);
      y += 18;

      const businessValues = buildBusinessValues(steps, detectedFlags, industry);
      const valCols = 2;
      const valW = (CONTENT_W - 10) / valCols;
      const valH = 42;

      for (let i = 0; i < Math.min(businessValues.length, 6); i++) {
        const col = i % valCols;
        const row = Math.floor(i / valCols);
        const x = MARGIN + col * (valW + 10);
        const vy = y + row * (valH + 6);
        const bv = businessValues[i];

        doc.roundedRect(x, vy, valW, valH, 4)
          .lineWidth(0.5).strokeColor(COLORS.dtGray).stroke();

        doc.fontSize(8).fillColor(COLORS.dtCyan)
          .text(`${bv.icon}  ${bv.title}`, x + 8, vy + 8, { width: valW - 16 });

        doc.fontSize(6.5).fillColor(COLORS.lightGray)
          .text(bv.description, x + 8, vy + 22, { width: valW - 16, lineBreak: true, height: 16 });
      }

      const valRows = Math.ceil(Math.min(businessValues.length, 6) / valCols);
      y += valRows * (valH + 6) + 10;

      // ══════════════════════════════════════════════════════
      // DASHBOARD STATS BAR
      // ══════════════════════════════════════════════════════
      const tileCount = metadata.totalTiles || Object.keys(dashboardData?.content?.tiles || {}).length || 0;
      const dynamicCount = metadata.dynamicFieldTiles || 0;
      const method = metadata.generationMethod || 'template';

      if (tileCount > 0) {
        doc.roundedRect(MARGIN, y, CONTENT_W, 34, 4).fill(COLORS.dtDark);

        const statItems = [
          { label: 'Dashboard Tiles', value: String(tileCount), color: COLORS.dtCyan },
          { label: 'Dynamic KPIs', value: String(dynamicCount), color: COLORS.dtGreen },
          { label: 'Journey Steps', value: String(steps.length), color: COLORS.dtPurple },
          { label: 'Generation', value: method.includes('ollama') ? 'AI Enhanced' : 'Template', color: COLORS.dtOrange },
        ];

        const statW = CONTENT_W / statItems.length;
        statItems.forEach((s, i) => {
          const sx = MARGIN + i * statW;
          doc.fontSize(12).fillColor(s.color)
            .text(s.value, sx + 10, y + 6, { width: statW - 20, align: 'center' });
          doc.fontSize(6).fillColor(COLORS.midGray)
            .text(s.label, sx + 10, y + 22, { width: statW - 20, align: 'center' });
        });

        y += 44;
      }

      // ══════════════════════════════════════════════════════
      // STEP DETAIL TABLE
      // ══════════════════════════════════════════════════════
      if (y < PAGE_H - 160) {
        doc.rect(MARGIN, y, CONTENT_W, 1).fill(COLORS.dtBlue);
        y += 10;

        doc.fontSize(10).fillColor(COLORS.dtBlue)
          .text('JOURNEY STEP DETAIL', MARGIN, y);
        y += 16;

        // Table header
        const colWidths = [28, 120, 150, 45, CONTENT_W - 28 - 120 - 150 - 45];
        const headers = ['#', 'Step', 'Business Rationale', 'Duration', 'Services'];

        doc.rect(MARGIN, y, CONTENT_W, 16).fill(COLORS.dtGray);
        let hx = MARGIN;
        headers.forEach((h, i) => {
          doc.fontSize(6.5).fillColor(COLORS.dtCyan)
            .text(h, hx + 4, y + 4, { width: colWidths[i] - 8 });
          hx += colWidths[i];
        });
        y += 16;

        // Table rows
        for (let i = 0; i < Math.min(steps.length, 6); i++) {
          if (y > PAGE_H - 80) break;
          const step = steps[i];
          const rowH = 24;
          const bg = i % 2 === 0 ? COLORS.dtCard : COLORS.dtDark;

          doc.rect(MARGIN, y, CONTENT_W, rowH).fill(bg);

          let rx = MARGIN;
          const rowData = [
            String(i + 1),
            formatStepName(step.stepName),
            truncateText(step.businessRationale || step.description || '', 70),
            `${step.estimatedDuration || '?'} min`,
            step.serviceName || '',
          ];

          rowData.forEach((cell, ci) => {
            doc.fontSize(6).fillColor(ci === 0 ? stepColors[i % stepColors.length] : COLORS.lightGray)
              .text(cell, rx + 4, y + 4, { width: colWidths[ci] - 8, lineBreak: true, height: rowH - 4, ellipsis: true });
            rx += colWidths[ci];
          });

          y += rowH;
        }
      }

      // ══════════════════════════════════════════════════════
      // FOOTER
      // ══════════════════════════════════════════════════════
      const footerY = PAGE_H - 36;
      doc.rect(0, footerY, PAGE_W, 36).fill(COLORS.dtDark);
      doc.rect(0, footerY, PAGE_W, 1).fill(COLORS.dtPurple);

      doc.fontSize(7).fillColor(COLORS.midGray)
        .text('Generated by Business Observability Forge  •  Dynatrace', MARGIN, footerY + 10, { width: CONTENT_W * 0.6 });

      doc.fontSize(7).fillColor(COLORS.dtCyan)
        .text('dynatrace.com', MARGIN + CONTENT_W * 0.8, footerY + 10, { width: CONTENT_W * 0.2, align: 'right' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// ── Helper functions ────────────────────────────────────────

function getIndustryIcon(industry) {
  const lower = (industry || '').toLowerCase();
  for (const [key, icon] of Object.entries(INDUSTRY_ICONS)) {
    if (lower.includes(key)) return icon;
  }
  return INDUSTRY_ICONS.default;
}

function formatStepName(name) {
  return (name || '').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2');
}

function truncateText(text, maxLen) {
  if (!text) return '';
  return text.length > maxLen ? text.substring(0, maxLen - 1) + '…' : text;
}

function buildObservedMetrics(flags, steps, industry) {
  const metrics = [];

  // Always present
  metrics.push({
    icon: '⏱️', title: 'End-to-End Duration',
    description: 'Full journey completion time across all steps and services',
    color: COLORS.dtCyan,
  });
  metrics.push({
    icon: '✅', title: 'Step Success Rate',
    description: 'Pass/fail ratio for each business step and substep',
    color: COLORS.dtGreen,
  });
  metrics.push({
    icon: '🔴', title: 'Error Detection',
    description: 'Real-time error tracking with root cause by service',
    color: '#EF4444',
  });

  // Dynamic based on detected fields
  if (flags.revenue)     metrics.push({ icon: '💰', title: 'Revenue Tracking',     description: 'Transaction revenue correlated with journey performance', color: COLORS.dtGreen });
  if (flags.conversion)  metrics.push({ icon: '📈', title: 'Conversion Funnel',    description: 'Step-by-step conversion rates from start to completion', color: COLORS.dtCyan });
  if (flags.nps)         metrics.push({ icon: '⭐', title: 'NPS / Satisfaction',    description: 'Customer satisfaction scores tied to journey experience', color: COLORS.dtYellow });
  if (flags.loyalty)     metrics.push({ icon: '🏆', title: 'Loyalty Analytics',     description: 'Loyalty tier impact on journey behavior and outcomes', color: COLORS.dtOrange });
  if (flags.churnRisk)   metrics.push({ icon: '⚠️', title: 'Churn Risk Scoring',   description: 'Early warning signals from journey drop-off patterns', color: '#EF4444' });
  if (flags.fraud)       metrics.push({ icon: '🔒', title: 'Fraud Detection',      description: 'Suspicious patterns flagged during transaction processing', color: '#EF4444' });
  if (flags.compliance)  metrics.push({ icon: '📋', title: 'Compliance Tracking',   description: 'Regulatory checkpoint monitoring and audit readiness', color: COLORS.dtBlue });
  if (flags.retention)   metrics.push({ icon: '🔄', title: 'Retention Signals',     description: 'Customer retention indicators across touchpoints', color: COLORS.dtPurple });
  if (flags.subscription) metrics.push({ icon: '📦', title: 'Subscription Health', description: 'Subscription lifecycle and renewal performance', color: COLORS.dtBlue });

  // Fill remaining slots with service-level metrics
  if (metrics.length < 9) {
    metrics.push({ icon: '🏗️', title: 'Service Dependencies', description: `${steps.length} services mapped with latency and error budgets`, color: COLORS.dtPurple });
  }
  if (metrics.length < 9) {
    metrics.push({ icon: '📊', title: 'Business Events (BizEvents)', description: 'Every step emits structured business events into Grail', color: COLORS.dtBlue });
  }

  return metrics.slice(0, 9);
}

function buildBusinessValues(steps, flags, industry) {
  const values = [];

  values.push({
    icon: '🎯', title: 'Journey-Centric Observability',
    description: `Full visibility into ${steps.length}-step ${formatIndustry(industry)} journey — from first touch to completion.`,
  });

  values.push({
    icon: '⚡', title: 'Proactive Issue Detection',
    description: 'Davis AI detects anomalies before customers are impacted, reducing MTTR by up to 90%.',
  });

  if (flags.revenue) {
    values.push({
      icon: '💰', title: 'Revenue Impact Quantification',
      description: 'Every technical issue is automatically correlated with revenue impact, prioritizing fixes by business value.',
    });
  }

  values.push({
    icon: '📈', title: 'Real-Time Business KPIs',
    description: 'Live dashboard with conversion rates, step durations, and customer experience metrics — no manual instrumentation.',
  });

  if (flags.nps || flags.satisfaction) {
    values.push({
      icon: '😊', title: 'Customer Experience Correlation',
      description: 'Link NPS and satisfaction scores directly to infrastructure and application performance.',
    });
  }

  values.push({
    icon: '🔗', title: 'Full-Stack Correlation',
    description: 'OpenTelemetry traces connect business events to infrastructure — one click from KPI to root cause.',
  });

  if (flags.compliance || flags.risk) {
    values.push({
      icon: '🛡️', title: 'Compliance & Risk Visibility',
      description: 'Automated monitoring of regulatory checkpoints with audit-ready dashboards.',
    });
  }

  if (flags.loyalty || flags.retention) {
    values.push({
      icon: '🔄', title: 'Retention & Loyalty Insights',
      description: 'Understand how platform performance directly impacts customer loyalty and lifetime value.',
    });
  }

  // Ensure we always have at least 4
  if (values.length < 4) {
    values.push({
      icon: '🤖', title: 'AI-Powered Analytics',
      description: 'Davis AI provides automatic root cause analysis and predictive insights across the journey.',
    });
  }

  return values.slice(0, 6);
}

function formatIndustry(industry) {
  return (industry || 'enterprise').replace(/[-_]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}
